# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zaragoza Accesible
email: ccamara@usj.es
description: > # this means to ignore newlines until "baseurl:"
  <b><a href="/about">Zaragoza Accesible</a></b> es un proyecto de mapeado colaborativo de
  aspectos relacionados con la discapacidad y la movilidad desarrollado en el marco de la <b><a href="/catedra">cátedra Bantierra - Fundación Adecco</a></b> de la
  <a href="http://etsa.usj.es">Escuela Técnica Superior de Arquitectura</a> de la
  <a href="http://usj.es">Universidad San Jorge</a>
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://zaccesible.usj.es" # the base hostname & protocol for your site
twitter_username: etsa_usj
github_username:  etsa-usj
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Custom variables:
kramdown:
  auto_ids: true # Auto-generate ID's for headings
authors: # Multiple authors: https://gist.github.com/ravasthi/1834570
  ccamara:
    name: Carlos Cámara
    display_name: Carlos Cámara
    web: http://carloscamara.es
    twitter: carlescamara
    github: ccamara
  CesarCanalis:
    name: César Canalís
    display_name: César Canalís
    github: CesarCanalis

# Prose settings (visit: https://github.com/prose/prose/wiki/Prose-Configuration)
prose:
  siteurl: 'http://zaccesible.usj.es'
  relativeLinks: 'http://zaccesible.usj.es/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "button"
          label: "Publicar"
          on: "Publicado"
          off: "Despublicado"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Mapas"
              value: "mapas"
            - name: "OpenStreetMap"
              value: "openstreetmap"
            - name: "Anuncios"
              value: "anuncios"
            - name: "Resultados"
              value: "resultados"
      - name: "comments"
        field:
            label: "Comments?"
            element: checkbox
            value: true
    pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "Published"
        field:
            label: "Publicado"
            element: checkbox
            value: false
    _drafts:
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          options:
            - name: "Post"
              value: "post"
            - name: "Page"
              value: "page"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Mapas"
              value: "mapas"
            - name: "OpenStreetMap"
              value: "openstreetmap"
            - name: "Anuncios"
              value: "anuncios"
            - name: "Resultados"
              value: "resultados"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
