# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Zaragoza Accesible
tagline:          'A Jekyll theme'
description:      > # this means to ignore newlines until "baseurl:"
  <b><a href="/about">Zaragoza Accesible</a></b> es un proyecto de mapeado colaborativo de
  aspectos relacionados con la discapacidad y la movilidad desarrollado desde el grupo de investigación <i>Arquitecturas OpenSource</i> de la
  <a href="http://etsa.usj.es">Escuela de Arquitectura y Tecnología</a> de la
  <a href="http://usj.es">Universidad San Jorge</a>
url:              https://zaccesible.usj.es
baseurl:          # the optional subpath of your site, e.g. "/blog"

#author:
  #name:           'Andrew Fong'
  #url:            https://twitter.com/fongandrewc

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            3.4.1
sidebar_home_link:  true
#github:
#  repo:             https://github.com/fongandrew/hydeout

disqus.shortname: zaccesible
google_analytics: UA-76289367-1

# Custom variables:
twitter_username: etsa_usj
github_username:  etsa-usj

kramdown:
  auto_ids: true # Auto-generate ID's for headings

authors: # Multiple authors: https://gist.github.com/ravasthi/1834570
  ccamara:
    name: Carlos Cámara
    display_name: Carlos Cámara
    web: http://carloscamara.es
    twitter: carlescamara
    github: ccamara
  CesarCanalis:
    name: César Canalís
    display_name: César Canalís
    github: CesarCanalis

# Prose settings (visit: https://github.com/prose/prose/wiki/Prose-Configuration)
prose:
  siteurl: 'http://zaccesible.usj.es'
  relativeLinks: 'http://zaccesible.usj.es/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "button"
          label: "Publicar"
          on: "Publicado"
          off: "Despublicado"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Mapas"
              value: "mapas"
            - name: "OpenStreetMap"
              value: "openstreetmap"
            - name: "Anuncios"
              value: "anuncios"
            - name: "Resultados"
              value: "resultados"
      - name: "comments"
        field:
            label: "Comments?"
            element: checkbox
            value: true
    pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "Published"
        field:
            label: "Publicado"
            element: checkbox
            value: false
    _drafts:
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          options:
            - name: "Post"
              value: "post"
            - name: "Page"
              value: "page"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Mapas"
              value: "mapas"
            - name: "OpenStreetMap"
              value: "openstreetmap"
            - name: "Anuncios"
              value: "anuncios"
            - name: "Resultados"
              value: "resultados"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
