# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zaragoza Accesible
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Proyecto de mapeado colaborativo de aspectos relacionados con la 
  discapacidad y la movilidad en Zaragoza que surge de la cátedra Bantierra
  - Fundación Adecco de la Escuela Técnica Superior de Arquitectura de la
  Universidad San Jorge
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: etsa_usj
github_username:  etsa-usj

# Build settings
markdown: kramdown

# Prose settings (visit: https://github.com/prose/prose/wiki/Prose-Configuration)
prose:
  siteurl: 'http://zaccesible.usj.es'
  relativeLinks: 'http://zaccesible.usj.es/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Mapas"
              value: "mapas"
            - name: "OpenStreetMap"
              value: "openstreetmap"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""